/*  ====================================================================================================================
	Thomas Ferguson
	CS 4480 - 001, Artificial Intelligence
	Dr. Kyu Koh
	November 19th, 2016

	This program is a functional, GUI/console chess game, written in C++ and using the GLUT OpenGL library.

	The BitmapFontClass.h and BitmapFontClass.cpp files are courtesy of Codehead (Karl W) and were retrieved from
	documents that came with his program, Codehead's Bitmap Font Generator (CBFG).  The class is used to
	read in the .bff file generated by CBFG, which is then used to draw font characters on the screen using OpenGL.
	The program was retrieved from:  http://www.codehead.co.uk/cbfg/

	The chess pieces rendered on the screen come from a font file called DiagramTTAlpha2.ttf
	The font used in conjunction with CBFG is courtesy of dacelle, a user on http://www.chess.com/.
	The font was retrieved from:  https://www.chess.com/download/view/fritz-fonts

	The negamax w/ alpha-beta pruning algorithm implementation largely came from https://en.wikipedia.org/wiki/Negamax
	and https://chessprogramming.wikispaces.com/Alpha-Beta, while the idea and values used for the piece type positional
	value arrays in chessGameTree.h came from https://chessprogramming.wikispaces.com/Simplified+evaluation+function.

	All other code was designed and written by the author, Thomas Ferguson.

	Note:  In order for the program to run and display the chess pieces correctly, the DiagramTTAlpha2.bff file
		   must be in the same folder as the source code and/or executable.
		   ** Absense of .bff file will very likely result in program crash or render the program unusable. **
	====================================================================================================================
*/

#include <GL/glut.h>
#include "functionPrototypes.h"
#include <iostream>
#include <fstream>

using namespace std;

int main(int argc, char **argv)
{
	// Initialize values, setup OpenGL GLUT callback functions.
	init(argc, argv);

	// Print instructions for user to console window.
	printInstructions();

	// Enter main loop.
	glutMainLoop();
}
